In [12]:
import pandas as pd
import numpy as np
import scipy
from scipy import stats  

# 1)Cutlets

1) A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units.
    A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5%
    significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.


Null Hypothisis : there is no difference in diameter between UnitA and UnitB.
Alternative Hypothisis : there is  difference in diameter between UnitA and UnitB. 
    
    It is two sample t test and alpha = 0.05(significance level)

In [2]:
data = pd.read_csv(r"C:\Users\Divya\Desktop\DS-Assignment\Hypothesis testing\Cutlets.csv")

In [3]:
data.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Unit A  35 non-null     float64
 1   Unit B  35 non-null     float64
dtypes: float64(2)
memory usage: 688.0 bytes


In [7]:
data['Unit A'].unique()

array([6.809 , 6.4376, 6.9157, 7.3012, 7.4488, 7.3871, 6.8755, 7.0621,
       6.684 , 6.8236, 7.393 , 7.5169, 6.9246, 6.9256, 6.5797, 6.8394,
       6.597 , 7.2705, 7.2828, 7.3495, 6.9438, 7.156 , 6.5341, 7.2854,
       6.9952, 6.8568, 7.2163, 6.6801, 6.9431, 7.0852, 6.7794, 7.2783,
       7.1561, 7.3943, 6.9405])

In [8]:
data['Unit B'].unique()

array([6.7703, 7.5093, 6.73  , 6.7878, 7.1522, 6.811 , 7.2212, 6.6606,
       7.2402, 7.0503, 6.881 , 7.4059, 6.7652, 6.038 , 7.1581, 7.024 ,
       6.6672, 7.4314, 7.307 , 6.7478, 6.8889, 7.422 , 6.5217, 7.1688,
       6.7594, 6.9399, 7.0133, 6.9182, 6.3346, 7.5459, 7.0992, 7.118 ,
       6.6965, 6.578 , 7.3875])

In [9]:
data['Unit A'].var()

0.08317945374789915

In [10]:
data['Unit B'].var()

0.11792400440336127

In [16]:
a = data['Unit A']
b = data['Unit B']

In [17]:
scipy.stats.ttest_ind(a,b,equal_var=False)

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.47231324819145404)

If P low, Null go
here p value is high and null stay, i.e. there is no difference in diameter between UnitA and UnitB

# 2) LabTAT

A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports
of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories.
TAT is defined as sample collected to report dispatch.
    Analyze the data and determine whether there is any difference in average TAT among the different laboratories 
    at 5% significance level.


Null Hypotisis :there is no difference in the average Turn Around Time (TAT)
               :L1=L2=L3=L4

Alternative Hypothisis : there is any difference in the average Turn Around Time (TAT)
                       :atleast there is one difference
    
    alpha : 0.05

In [34]:
df = pd.read_csv(r"C:\Users\Divya\Desktop\DS-Assignment\Hypothesis testing\labTAT.csv")
df.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laboratory 1  120 non-null    float64
 1   Laboratory 2  120 non-null    float64
 2   Laboratory 3  120 non-null    float64
 3   Laboratory 4  120 non-null    float64
dtypes: float64(4)
memory usage: 3.9 KB


In [36]:
df['Laboratory 1'].var()

173.54356806022412

In [37]:
df['Laboratory 2'].var()

223.71525108543426

In [38]:
df['Laboratory 3'].var()

273.53960699579824

In [39]:
df['Laboratory 4'].var()

227.55963186974788

In [59]:
f_statistic,p_value = stats.f_oneway(df['Laboratory 1'],df['Laboratory 2'],df['Laboratory 3'],df['Laboratory 4'])
print("F-statistic:", f_statistic)
print("P-value:", p_value)

F-statistic: 118.70421654401437
P-value: 2.1156708949992414e-57


p high null stay, and there is no difference in the average Turn Around Time

# 3)Byer ratio

Sales of products in four different regions is tabulated for males and females.
Find if male-female buyer rations are similar across regions.

Ho : all Proportion are equal

Ha : all Proportion are not equal    

In [62]:
df1 = pd.read_csv(r"C:\Users\Divya\Desktop\DS-Assignment\Hypothesis testing\BuyerRatio.csv")
df1.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [64]:
Observed_values = np.array([[50,142,131,70],[435,1523,1356,750]])

In [65]:
Observed_values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [66]:
stats.chi2_contingency(Observed_values)

Chi2ContingencyResult(statistic=1.595945538661058, pvalue=0.6603094907091882, dof=3, expected_freq=array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

alpha = 0.05

pvalue = 0.66 which is greater than alpha,

Ho stays i.e. all proportion are equal

# 4) CustomerOrderForm.

TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms.
Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether 
the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager 
draw appropriate inferences.

In [127]:
df2 = pd.read_csv(r"C:\Users\Divya\Desktop\DS-Assignment\Hypothesis testing\Costomer+OrderForm.csv")
df2.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

Ho :  there is no variation in defective %  by centre.
    
Ha :   there is  variation in defective %  by centre.  
    

In [128]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Phillippines  300 non-null    object
 1   Indonesia     300 non-null    object
 2   Malta         300 non-null    object
 3   India         300 non-null    object
dtypes: object(4)
memory usage: 9.5+ KB


In [129]:
df2['Phillippines'].unique()

array(['Error Free', 'Defective'], dtype=object)

In [130]:
df2['Indonesia'].unique()

array(['Error Free', 'Defective'], dtype=object)

In [132]:
df2['Phillippines'].value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [133]:
df2['Indonesia'].value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [134]:
df2['Malta'].value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [135]:
df2['India'].value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [136]:
df2_details = np.array([[271,29],[267,33],[269,31],[280,20]])
df2_details

array([[271,  29],
       [267,  33],
       [269,  31],
       [280,  20]])

In [137]:
stats.chi2_contingency(df2_details)

Chi2ContingencyResult(statistic=3.8589606858203545, pvalue=0.2771020991233144, dof=3, expected_freq=array([[271.75,  28.25],
       [271.75,  28.25],
       [271.75,  28.25],
       [271.75,  28.25]]))

In [139]:
chi2, p, dof, expected = stats.chi2_contingency(df2_details)
print("Chi-squared statistic:", chi2)
print("P-value:", p)

Chi-squared statistic: 3.8589606858203545
P-value: 0.2771020991233144


alpha = 0.05 

p_value is greater than alpha.hence Null stay i.e.there is no variation in defective % by centre. 